/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#5b4000",
        "surface-container-low": "#1b1b1f",
        "surface-container-lowest": "#0d0e11",
        "background": "#121316",
        "surface-dim": "#121316",
        "secondary": "#d4c78f",
        "surface-container-high": "#292a2d",
        "on-surface-variant": "#d0c5af",
        "surface-tint": "#e9c349",
        "surface-variant": "#343538",
        "on-error": "#690005",
        "primary-fixed": "#ffe088",
        "tertiary-container": "#d5ad62",
        "on-secondary": "#383006",
        "on-secondary-fixed-variant": "#4f471b",
        "primary-fixed-dim": "#e9c349",
        "error": "#ffb4ab",
        "outline": "#99907c",
        "surface-container-highest": "#343538",
        "on-primary-container": "#554300",
        "inverse-surface": "#e3e2e6",
        "inverse-primary": "#735c00",
        "on-tertiary-fixed": "#271900",
        "secondary-fixed-dim": "#d4c78f",
        "on-primary-fixed-variant": "#574500",
        "surface-container": "#1f1f23",
        "tertiary-fixed-dim": "#eac173",
        "surface-bright": "#38393c",
        "on-tertiary": "#412d00",
        "primary-container": "#d4af37",
        "on-primary": "#3c2f00",
        "on-tertiary-fixed-variant": "#5d4200",
        "secondary-fixed": "#f1e3a9",
        "on-secondary-container": "#c2b57f",
        "on-primary-fixed": "#241a00",
        "inverse-on-surface": "#2f3034",
        "primary": "#f2ca50",
        "on-surface": "#e3e2e6",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#211b00",
        "surface": "#121316",
        "tertiary-fixed": "#ffdea5",
        "tertiary": "#f3c87a",
        "secondary-container": "#4f471b",
        "error-container": "#93000a",
        "outline-variant": "#4d4635",
        "on-background": "#e3e2e6"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "space-xl": "2.5rem",
        "space-sm": "0.5rem",
        "gutter-mobile": "0.75rem",
        "margin": "3rem",
        "gutter": "1.5rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "margin-mobile": "1rem"
      },
      fontFamily: {
        "display-lg-mobile": ["EB Garamond"],
        "label-sm": ["Geist"],
        "headline-sm": ["EB Garamond"],
        "display-lg": ["EB Garamond"],
        "label-md": ["Geist"],
        "body-sm": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "headline-md": ["EB Garamond"],
        "headline-lg-mobile": ["EB Garamond"],
        "label-lg": ["Geist"],
        "body-lg": ["Hanken Grotesk"],
        "headline-lg": ["EB Garamond"],
        "Geist": ["Geist"],  // Added to generate font-Geist utility class
        "EB_Garamond": ["EB Garamond"],  // Added to generate font-EB_Garamond utility class
        "Hanken_Grotesk": ["Hanken Grotesk"]  // Added to generate font-Hanken_Grotesk utility class
      },
      fontSize: {
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.12em", fontWeight: "600" }],
        "headline-sm": ["22px", { lineHeight: "30px", letterSpacing: "0em", fontWeight: "500" }],
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "label-md": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "0em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-lg": ["13px", { lineHeight: "18px", letterSpacing: "0.06em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.015em", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}